name: CI Pipeline
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate Prompts
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Validate prompt format
        run: python scripts/validate_prompts.py
        
      - name: Check markdown formatting
        run: |
          npm install -g prettier markdownlint-cli
          prettier --check "**/*.md"
          markdownlint "**/*.md"
          
      - name: Validate catalog consistency
        run: python scripts/validate_catalog.py
        
      - name: Check for broken links
        run: python scripts/check_links.py

  security:
    runs-on: ubuntu-latest
    name: Security Scan
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Run security scan
        uses: securecodewarrior/github-action-add-sarif@v1
        with:
          sarif-file: 'security-scan-results.sarif'

  deploy:
    runs-on: ubuntu-latest
    name: Deploy Documentation
    needs: [validate, security]
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Generate catalog
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python scripts/generate_catalog.py
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
