name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: |
          npm ci
          npm install -g @vscode/vsce

      - name: Build Extension
        run: |
          npm run compile

      - name: Package Extension
        run: |
          vsce package

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: "*.vsix"
          generate_release_notes: true

      - name: Publish to VS Code Marketplace
        if: success() && !contains(github.ref, '-pre')
        run: |
          vsce publish -p ${{ secrets.VSCE_PAT }}
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
